### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bihanghang** [evolify/translator#1]
My dear
It doesn't work
like this 
![](https://raw.githubusercontent.com/Bihanghang/Test/master/MarkDownPictures/tlfailure.PNG)
Can you help to solve it ?

**Comment by evolify** [comment]
Please provide details information.

**Comment by Bihanghang** [comment]
Waiting your reply

**Comment by evolify** [comment]
Can you speak chinese?

**Comment by Bihanghang** [comment]
额。。。老哥，你这个咋报错了呢

**Comment by evolify** [comment]
应该是你环境的问题，你google搜索ETIMDOUT，貌似有很多类似问题。我这个只是简单的爬去一个网页，你换个机器试试行不行，我这边没win7系统，也没法测试啊，之前在mac和win10上都是可以的。

**Comment by Bihanghang** [comment]
好的吧<0-0>
